version: '3.3'
services:
  db:
    image: vsamov/mysql-5.1.73:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'quote_manager'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: